### PR TITLE
New method that uses origins to load the assembly

### PR DESCRIPTION
**Pull request by moorts**
Is there a reason to keep the old one, or should I just change it?

Also did I do something stupid somewhere?

### CODE REVIEW

**Review by felixhir — APPROVED** [review]
Looks like a reasonable test and as if the origins work as intended.

What 'old' method are you talking about?

**Comment by moorts** [comment]
Now there are two methods `load_asm_file` and `load_asm_file_with_origins`, the first is probably useless

**Comment by nico1207** [comment]
In my opinion, Assembler.assemble() should already output the correct bytes with their origins. It's weird that the user should have to arrange the pieces himself.

**Comment by moorts** [comment]
Should Assembler.assemble() then output a Vector<u8> containing all bytes until the last instructions with empty bytes in between chunks of code?

**Comment by nico1207** [comment]
> 

That would make more sense IMO

**Comment by felixhir** [comment]
How do we want to represent empty bytes? Should we switch to a Vector of options in this case? Just leave them at 0? What would be the best way to handle this so the emulator has to do the least amount of additional checks?

**Comment by nico1207** [comment]
> How do we want to represent empty bytes? Should we switch to a Vector of options in this case? Just leave them at 0? What would be the best way to handle this so the emulator has to do the least amount of additional checks?

It should be 0

**Pull request closed without merging**
