### PR TITLE
Feature/line mapping

### LINKED ISSUE #40: Map lines to memory bytes
The assembler should have a method to return the line corresponding to a certain byte so we can show the current "position of execution" in the frontend.

Should this be done by returning a large map like `fn get_line_mapping() -> HashMap<Range, i32>` or do we want a method like 
`fn get_line_of_byte(byte: i32) -> i32`?

### PR DESCRIPTION
**Pull request by felixhir**
Closes #40 

The `assembler` struct now offers the method `get_line_map()` that returns a map containing all bytes that will be output if the code is assembled (referring to their indices starting at 0), mapped to the corresponding line (starting at 0).

I should have covered the biggest pain points (IF and MACRO) with respective tests, so everything _should_ run smoothly.

### CODE REVIEW

**Comment by felixhir** [comment]
We can of course change the return type, I don't even think the origin integration (which I will get to tomorrow) is needed to do so.
Is there any specific reason you would want that change?

**Comment by nico1207** [comment]
Just a minor performance optimization, aka premature optimization, aka the root of all evil

**Comment by felixhir** [comment]
I just understood what you are aiming for. In that case I will implement this alongside the origins for the assembler. If I am not mistaken both methods should return an `array` - not a `vector` afterwards, right?

**Comment by nico1207** [comment]
What's the difference? I don't think it matters

**Comment by felixhir** [comment]
An array is of fixed size, a vector can be extended dynamically

**Pull request merged**
